version: "3.7"
services:
  ror:
    build: ./ror
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./ror:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    restart: always

  nuxt:
    build: ./nuxt
    command: npm run dev
    volumes:
      - ./nuxt:/app
    ports:
      - "3333:3333"
    tty: true
    restart: always

  db:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:1.17.9-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  database:
    driver: local
